import httpx
import os
import asyncio
from datetime import datetime
from fastapi import FastAPI
from nicegui import app, ui
from sqlmodel import Field, Session, SQLModel, create_engine, select
from typing import Optional
from fpdf import FPDF
from engine.scanner import run_full_scan, capture_screenshot
from apscheduler.schedulers.background import BackgroundScheduler
from dotenv import load_dotenv

# --- MEMUAT KREDENSIAL DARI FILE .ENV ---
load_dotenv()

# --- KONFIGURASI TELEGRAM ---
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# [TAMBAHAN] Daftar untuk mencatat tab browser yang sedang aktif
aktif_clients = []

os.makedirs("screenshots", exist_ok=True)
os.makedirs("reports", exist_ok=True)

# --- 1. SETUP DATABASE ---
class Target(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    url: str
    ip_address: Optional[str] = "Belum Discan"
    last_hash: Optional[str] = None
    status: str = "Belum Discan"
    score: int = 100
    last_alerts: Optional[str] = ""        
    remediation_notes: Optional[str] = ""  

class ScanHistory(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    target_id: int
    timestamp: str
    score: int

sqlite_url = "sqlite:///database.db"
engine = create_engine(sqlite_url)
SQLModel.metadata.create_all(engine)

def get_targets_data():
    with Session(engine) as session:
        return session.exec(select(Target)).all()

# --- 2. GENERATOR LAPORAN PDF ---
def generate_pdf_report(target_url, score, alerts, remediations):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Cyber-themed header
    pdf.set_fill_color(10, 14, 23)
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_text_color(0, 212, 255)
    pdf.set_font("Courier", 'B', 20)
    from fpdf.enums import XPos, YPos
    pdf.cell(0, 25, text="DEVSECOPS CYBER PATROL", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    pdf.set_text_color(150, 150, 150)
    pdf.set_font("Courier", '', 10)
    pdf.cell(0, 5, text="Security Audit Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    
    pdf.set_text_color(0, 0, 0)
    pdf.ln(15)
    
    # Report metadata
    pdf.set_font("Courier", 'B', 14)
    pdf.set_text_color(0, 100, 150)
    pdf.cell(0, 10, text="TARGET INTELLIGENCE", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    
    pdf.set_font("Courier", '', 11)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, text=f"Target: {target_url}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 8, text=f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 8, text=f"Security Score: {score}/100", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # Score indicator
    if score >= 80:
        pdf.set_text_color(0, 150, 50)
        status = "SECURE"
    elif score >= 50:
        pdf.set_text_color(200, 150, 0)
        status = "WARNING"
    else:
        pdf.set_text_color(200, 0, 50)
        status = "CRITICAL"
    pdf.cell(0, 8, text=f"Status: {status}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(10)
    pdf.set_font("Courier", 'B', 14)
    pdf.set_text_color(0, 100, 150)
    pdf.cell(0, 10, text="VULNERABILITY FINDINGS", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    
    pdf.set_font("Courier", '', 10)
    if not alerts or alerts[0] == "Tidak ada ancaman terdeteksi.":
        pdf.set_text_color(0, 150, 50)
        pdf.cell(0, 10, text="No critical vulnerabilities detected. System is secure.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        pdf.set_text_color(180, 50, 50)
        for alert in alerts:
            clean_alert = alert.encode('ascii', 'ignore').decode('ascii').replace('*', '')
            pdf.multi_cell(0, 7, text=f"> {clean_alert}")
            pdf.ln(3)

    pdf.ln(10)
    pdf.set_font("Courier", 'B', 14)
    pdf.set_text_color(0, 100, 150)
    pdf.cell(0, 10, text="REMEDIATION RECOMMENDATIONS", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)
    
    pdf.set_font("Courier", '', 10)
    if not remediations or remediations[0] == "Sistem optimal. Pertahankan.":
        pdf.set_text_color(0, 150, 50)
        pdf.cell(0, 10, text="Maintain current security configuration.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        pdf.set_text_color(50, 100, 180)
        for rem in remediations:
            clean_rem = rem.encode('ascii', 'ignore').decode('ascii').replace('*', '')
            pdf.multi_cell(0, 7, text=f"[+] {clean_rem}")
            pdf.ln(3)
    
    # Footer
    pdf.set_y(-25)
    pdf.set_font("Courier", '', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, text="Generated by DEVSECOPS Cyber Patrol System", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    pdf.cell(0, 5, text="For internal use only | Confidential", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')

    safe_url = target_url.replace('https://', '').replace('http://', '').replace('/', '_')
    filename = f"reports/Audit_{safe_url}.pdf"
    pdf.output(filename)
    return filename

# --- 3. LOGIKA TELEGRAM & PATROLI ---
async def kirim_telegram(pesan: str, photo_path: str = None, doc_path: str = None):
    async with httpx.AsyncClient() as client:
        try:
            if photo_path and os.path.exists(photo_path):
                url_tele = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendPhoto"
                with open(photo_path, "rb") as f:
                    await client.post(url_tele, data={"chat_id": CHAT_ID, "caption": pesan}, files={"photo": f})
            elif doc_path and os.path.exists(doc_path):
                url_tele = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendDocument"
                with open(doc_path, "rb") as f:
                    await client.post(url_tele, data={"chat_id": CHAT_ID, "caption": pesan}, files={"document": f})
            else:
                url_tele = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
                await client.post(url_tele, json={"chat_id": CHAT_ID, "text": pesan})
        except: pass

async def patroli_core_logic():
    with Session(engine) as session:
        targets = session.exec(select(Target)).all()
        for target in targets:
            hasil = await run_full_scan(target.url)
            # Integrasi Deteksi Cloudflare
            is_cf = hasil['cf_info'].get('is_cloudflare', False)
            alerts = []
            remediations = []
            score = 100
            photo_evidence = None
            if is_cf:
                target.ip_address = "Cloudflare Proxy" # Timpa IP jika lewat CF
                alerts.append("🛡️ DETECTED: Website dilindungi oleh Cloudflare WAF.")
                remediations.append("CLOUDFLARE: Target menggunakan perlindungan WAF. "
                                    "Serangan langsung ke IP (Direct IP Attack) tidak dimungkinkan. "
                                    "Gunakan teknik 'Cloudflare Bypass' atau cari 'Origin IP' jika diperlukan untuk audit mendalam.")
            # Jika bukan Cloudflare tapi DNS gagal (Firewall Kampus)
            elif hasil['ip_info'].get('protected'):
                target.ip_address = "Protected/Firewall"
                alerts.append("🛡️ INFO: Server memiliki proteksi Firewall internal.")
                remediations.append("NETWORK: DNS terproteksi. Kemungkinan server berada di jaringan internal kampus (Intranet).")
            # Jika DNS/firewall protection (tambahan info, tidak overwrite alert utama)
            if hasil['ip_info'].get('protected'):
                alerts.append("🛡️ INFO: Server memiliki proteksi DNS/Firewall ekstra.")
                remediations.append("NETWORK: DNS tidak dapat diresolusi secara publik. Server kemungkinan besar berada di balik WAF (Cloudflare/Fortigate) atau jaringan VPN internal kampus. Ini adalah konfigurasi pertahanan yang baik.")
            
            new_hash = hasil['defacement'].get('content_hash')
            if target.last_hash and target.last_hash != new_hash:
                alerts.append("🚨 DEFACEMENT DETECTED! Konten web berubah drastis.")
                remediations.append("DEFACEMENT: Segera pulihkan website dari backup terbaru. Periksa log akses server.")
                score -= 50
                photo_evidence = f"screenshots/evidence_{target.id}.png"
                await capture_screenshot(target.url, photo_evidence)
                
            open_ports = hasil['ports'].get('open_ports', [])
            if open_ports:
                alerts.append(f"⚠️ PORT TERBUKA: Port {open_ports} terekspos ke publik.")
                remediations.append(f"FIREWALL: Tutup akses publik ke port {open_ports} menggunakan firewall (UFW/Iptables).")
                score -= 30
                
            fuzz_paths = hasil['fuzz'].get('exposed_paths', [])
            if fuzz_paths:
                alerts.append(f"🔥 SENSITIVE DATA: Path bocor ({', '.join(fuzz_paths)})")
                remediations.append("FILE BOCOR: Pindahkan file sensitif ke luar direktori publik atau atur hak akses server.")
                score -= 40
                
            api_keys = hasil['api'].get('leaked_keys', [])
            if api_keys:
                alerts.append(f"🔑 API KEY BOCOR: Indikasi {', '.join(api_keys)}")
                remediations.append("SECRETS: Segera cabut (revoke) kunci API yang bocor dan gunakan Environment Variables (.env).")
                score -= 30

            ssl_days = hasil['ssl'].get('days_left', -1)
            if 0 < ssl_days < 7:
                alerts.append(f"🔒 SSL KRITIS: Kedaluwarsa dalam {ssl_days} hari")
                remediations.append("SERTIFIKAT: Perbarui sertifikat SSL segera menggunakan Certbot atau hubungi pihak hosting.")
                score -= 20
                
            broken_links = hasil['links'].get('broken_links', [])
            if broken_links:
                alerts.append(f"🔗 BROKEN LINKS: {len(broken_links)} tautan mati.")
                remediations.append("TAUTAN: Hapus atau perbarui tautan yang mati agar tidak diambil alih oleh peretas (Broken Link Hijacking).")
                score -= 15
                
            domain_days = hasil['whois'].get('domain_days_left', -1)
            if 0 < domain_days < 14:
                alerts.append(f"🌐 DOMAIN KRITIS: Hangus dalam {domain_days} hari")
                remediations.append("DOMAIN: Lakukan perpanjangan (renewal) domain di registrar Anda.")
                score -= 20

            headers_missing = hasil['headers'].get('headers_missing', [])
            if headers_missing:
                score -= (len(headers_missing) * 5)
                alerts.append(f"🟡 HEADERS LEMAH: {len(headers_missing)} lapisan hilang.")
                remediations.append("HEADERS: Konfigurasi web server untuk menambahkan Security Headers seperti CSP, HSTS, dan X-Frame-Options.")

            score = max(0, score)

            target.ip_address = hasil['ip_info'].get('ip_address', 'Tidak diketahui')
            target.last_hash = new_hash
            target.score = score
            target.status = "Kritis" if score < 50 else ("Peringatan" if score < 80 else "Aman")
            target.last_alerts = "\n".join(alerts) if alerts else "Tidak ada ancaman terdeteksi."
            target.remediation_notes = "\n".join(remediations) if remediations else "Sistem optimal. Pertahankan."
            session.add(target)
            
            history = ScanHistory(target_id=target.id, timestamp=datetime.now().strftime('%H:%M'), score=score)
            session.add(history)
            session.commit()

            if alerts:
                pesan = f"🛡️ LAPORAN {target.url}\nSkor: {score}/100\n\n" + "\n".join(alerts)
                await kirim_telegram(pesan, photo_path=photo_evidence)
                if score < 50:
                    pdf_path = generate_pdf_report(target.url, score, alerts, remediations)
                    await kirim_telegram(f"📄 Laporan Audit & Remediasi untuk {target.url}", doc_path=pdf_path)

    # --- FITUR BROADCAST REFRESH (VERSI FINAL & STABIL) ---
    # Karena dijalankan dari background task, ini otomatis terkirim ke semua client
    ui.run_javascript('window.location.reload()')
    
    print("[*] Siklus patroli selesai & Perintah Refresh disiarkan ke semua client.")

# --- 4. TAMPILAN DASHBOARD LANJUTAN ---
@ui.page('/')
def index_page():
    ui.colors(primary='#0f172a')
    
    # Custom CSS - Cybersecurity Theme
    ui.add_css('''
        @media (max-width: 1280px) {
            .cyber-card {
                width: 100% !important;
                min-width: 0 !important;
                max-width: 100% !important;
            }
            .target-row-responsive {
                flex-direction: column !important;
                align-items: stretch !important;
            }
        }
        @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&family=Inter:wght@300;400;500;600;700;800&display=swap');
        
        :root {
            --cyber-dark: #0a0e17;
            --cyber-darker: #050810;
            --cyber-blue: #00d4ff;
            --cyber-green: #00ff88;
            --cyber-red: #ff3366;
            --cyber-amber: #ffaa00;
            --cyber-purple: #a855f7;
            --cyber-card: #111827;
            --cyber-border: #1e293b;
        }
        
        * { box-sizing: border-box; }
        
        body { 
            background: linear-gradient(135deg, var(--cyber-darker) 0%, var(--cyber-dark) 50%, #0f172a 100%);
            background-attachment: fixed;
            font-family: 'Inter', sans-serif;
        }
        
        .cyber-container {
            background: rgba(17, 24, 39, 0.7);
            backdrop-filter: blur(10px);
            border: 1px solid var(--cyber-border);
        }
        
        .cyber-card {
            background: linear-gradient(180deg, rgba(17, 24, 39, 0.9) 0%, rgba(10, 14, 23, 0.95) 100%);
            border: 1px solid var(--cyber-border);
            border-radius: 12px;
            transition: all 0.3s ease;
        }
        .cyber-card:hover {
            border-color: var(--cyber-blue);
            box-shadow: 0 0 20px rgba(0, 212, 255, 0.15), 0 8px 32px rgba(0, 0, 0, 0.4);
            transform: translateY(-2px);
        }
        
        .cyber-card-secure { border-left: 4px solid var(--cyber-green); }
        .cyber-card-warning { border-left: 4px solid var(--cyber-amber); }
        .cyber-card-danger { border-left: 4px solid var(--cyber-red); }
        
        .cyber-btn {
            background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
            border: 1px solid var(--cyber-border);
            color: var(--cyber-blue);
            font-family: 'JetBrains Mono', monospace;
            font-weight: 600;
            padding: 10px 20px;
            border-radius: 8px;
            transition: all 0.2s ease;
            text-transform: uppercase;
            letter-spacing: 1px;
            font-size: 12px;
        }
        
        .cyber-btn:hover {
            background: linear-gradient(135deg, var(--cyber-blue) 0%, #0099cc 100%);
            color: var(--cyber-darker);
            box-shadow: 0 0 15px rgba(0, 212, 255, 0.4);
        }
        
        .cyber-btn-primary {
            background: linear-gradient(135deg, var(--cyber-blue) 0%, #0099cc 100%);
            color: var(--cyber-darker);
            border: none;
        }
        
        .cyber-btn-primary:hover {
            box-shadow: 0 0 25px rgba(0, 212, 255, 0.6);
        }
        
        .cyber-input {
            background: rgba(255,255,255,0.85);
            border: 2px solid #00d4ff;
            color: #111827 !important;
            padding: 12px 16px;
            border-radius: 8px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 16px;
            caret-color: #00d4ff;
            font-weight: 700;
            letter-spacing: 0.5px;
            box-shadow: 0 0 0 2px #00d4ff33;
        }
        .cyber-input:focus {
            border-color: #00d4ff;
            box-shadow: 0 0 0 3px #00d4ff88;
            outline: none;
            color: #111827 !important;
            background: #fff;
        }
        .cyber-input::placeholder {
            color: #222 !important;
            opacity: 1;
            font-weight: 700;
            letter-spacing: 0.5px;
            text-shadow: none;
        }
        
        .cyber-score-secure { color: var(--cyber-green); text-shadow: 0 0 10px rgba(0, 255, 136, 0.5); }
        .cyber-score-warning { color: var(--cyber-amber); text-shadow: 0 0 10px rgba(255, 170, 0, 0.5); }
        .cyber-score-danger { color: var(--cyber-red); text-shadow: 0 0 10px rgba(255, 51, 102, 0.5); }
        
        .cyber-status-secure { 
            background: rgba(0, 255, 136, 0.15); 
            color: var(--cyber-green); 
            border: 1px solid rgba(0, 255, 136, 0.3);
        }
        .cyber-status-warning { 
            background: rgba(255, 170, 0, 0.15); 
            color: var(--cyber-amber); 
            border: 1px solid rgba(255, 170, 0, 0.3);
        }
        .cyber-status-danger { 
            background: rgba(255, 51, 102, 0.15); 
            color: var(--cyber-red); 
            border: 1px solid rgba(255, 51, 102, 0.3);
        }
        
        .cyber-terminal {
            background: rgba(5, 8, 16, 0.95);
            border: 1px solid #1e3a5f;
            font-family: 'JetBrains Mono', monospace;
            color: var(--cyber-green);
            border-radius: 8px;
            box-shadow: inset 0 0 30px rgba(0, 212, 255, 0.05);
        }
        
        .cyber-header {
            background: linear-gradient(180deg, rgba(10, 14, 23, 0.98) 0%, rgba(10, 14, 23, 0.9) 100%);
            border-bottom: 1px solid var(--cyber-border);
            backdrop-filter: blur(20px);
        }
        
        .cyber-title {
            font-family: 'JetBrains Mono', monospace;
            background: linear-gradient(90deg, var(--cyber-blue), var(--cyber-green));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        
        .cyber-glow {
            animation: cyberGlow 2s ease-in-out infinite alternate;
        }
        
        @keyframes cyberGlow {
            from { box-shadow: 0 0 5px rgba(0, 212, 255, 0.3); }
            to { box-shadow: 0 0 20px rgba(0, 212, 255, 0.6); }
        }
        
        .scan-line {
            position: absolute;
            width: 100%;
            height: 2px;
            background: linear-gradient(90deg, transparent, var(--cyber-blue), transparent);
            animation: scanLine 3s linear infinite;
        }
        
        @keyframes scanLine {
            0% { top: 0; opacity: 0; }
            10% { opacity: 1; }
            90% { opacity: 1; }
            100% { top: 100%; opacity: 0; }
        }
        
        .pulse-dot {
            animation: pulse 2s infinite;
        }
        
        @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.5; }
        }
        
        /* Button Cancel (grey) override for better contrast */
        /* Tombol Cancel benar-benar kontras dan tidak transparan di semua state */
        .q-btn[color=grey], .q-btn[flat][color=grey],
        .q-btn[color=grey][disabled], .q-btn[flat][color=grey][disabled],
        .q-btn[color=grey][aria-disabled="true"], .q-btn[flat][color=grey][aria-disabled="true"] {
            color: #fff !important;
            background: #00d4ff !important;
            border: 2px solid #00d4ff !important;
            font-weight: bold !important;
            letter-spacing: 1px !important;
            text-shadow: 0 0 2px #000a !important;
            box-shadow: 0 0 8px #00d4ff44 !important;
            opacity: 1 !important;
            filter: brightness(1.1) !important;
            pointer-events: auto !important;
        }
        .q-btn[color=grey]:hover, .q-btn[flat][color=grey]:hover,
        .q-btn[color=grey][disabled]:hover, .q-btn[flat][color=grey][disabled]:hover,
        .q-btn[color=grey][aria-disabled="true"]:hover, .q-btn[flat][color=grey][aria-disabled="true"]:hover {
            color: #111827 !important;
            background: #fff !important;
            border-color: #00d4ff !important;
            opacity: 1 !important;
        }
        /* Responsive adjustments */
        @media (max-width: 768px) {
            .cyber-card {
                margin-bottom: 16px;
                width: 100% !important;
                min-width: 0 !important;
                max-width: 100% !important;
            }
            .cyber-btn { padding: 8px 16px; font-size: 11px; }
            .target-row-responsive {
                flex-direction: column !important;
                align-items: stretch !important;
            }
        }
        
        /* Scrollbar styling */
        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-track { background: var(--cyber-darker); }
        ::-webkit-scrollbar-thumb { background: var(--cyber-border); border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: var(--cyber-blue); }
    ''')
    
    # --- FITUR ANIMASI TERMINAL BARU ---
    async def jalankan_audit_manual():
        with ui.dialog() as progress_dialog, ui.card().classes('w-[600px] p-6 cyber-card cyber-glow'):
            with ui.row().classes('w-full items-center mb-4'):
                ui.spinner('orbit', size='lg', color='cyan')
                ui.label('INITIATING SCAN SEQUENCE...').classes('font-bold text-xl tracking-widest text-cyan-400 font-mono ml-4')
            
            # Animated scan line
            with ui.element('div').classes('relative overflow-hidden h-1 w-full mb-4'):
                ui.element('div').classes('scan-line')
            
            terminal = ui.log(max_lines=12).classes('w-full h-48 cyber-terminal p-4')
            terminal.push("[*] Establishing secure connection to target...")
            terminal.push("[*] Loading 8 parallel sensor modules...")
            
            langkah_proses = [
                "[>] Module 1: HTTP Security Headers Analysis...",
                "[>] Module 2: Defacement Hash Calculation (SHA-256)...",
                "[>] Module 3: SSL/TLS Certificate Validation...",
                "[>] Module 4: Open Port Discovery (21, 22, 3306)...",
                "[>] Module 5: Directory Fuzzing & Sensitive Files...",
                "[>] Module 6: API Key Leak Detection (Regex)...",
                "[>] Module 7: Broken Link Analysis...",
                "[>] Module 8: WHOIS Domain Intelligence...",
                "[*] Compiling vulnerability findings...",
                "[*] Calculating final security score...",
                "[+] Generating PDF report & Telegram notification..."
            ]
            
            def update_terminal():
                if langkah_proses:
                    terminal.push(langkah_proses.pop(0))
            
            log_timer = ui.timer(0.8, update_terminal)
            
        progress_dialog.open()
        
        await patroli_core_logic() 
        
        log_timer.cancel()
        progress_dialog.close()
        
        # Pesan notifikasi sukses
        ui.notify('✓ Scan Complete - Dashboard Updated', color='positive')

    with ui.header().classes('cyber-header items-center justify-between px-6 py-4 shadow-lg'):
        with ui.row().classes('items-center gap-3'):
            # Cyber shield icon with glow
            with ui.element('div').classes('relative'):
                ui.icon('security', size='xl', color='cyan').classes('text-3xl')
                ui.element('div').classes('absolute -inset-1 bg-cyan-500/20 rounded-full blur-lg')
            ui.label('PATROLI-WEB').classes('font-bold text-xl tracking-wider text-white')
            ui.label('COMMAND CENTER').classes('font-light text-cyan-400/70 text-lg font-mono')
            with ui.row().classes('items-center gap-2 ml-4'):
                ui.element('div').classes('w-2 h-2 bg-green-500 rounded-full pulse-dot')
                ui.label('ONLINE').classes('text-green-400 font-mono text-xs tracking-widest')
        with ui.row().classes('items-center gap-3'):
            ui.button('INITIATE SCAN', on_click=jalankan_audit_manual, icon='radar').classes('cyber-btn cyber-btn-primary')

    with ui.column().classes('w-full p-6 max-w-7xl mx-auto'):
        with ui.row().classes('w-full items-end justify-between mb-6'):
            with ui.column().classes('gap-1'):
                ui.label('DASHBOARD').classes('text-2xl font-bold text-white tracking-wider font-mono')
                ui.label('Real-time threat monitoring & prescriptive remediation').classes('text-cyan-400/60 text-sm font-mono')
            with ui.row().classes('items-center gap-2 text-cyan-400/50 text-xs font-mono'):
                ui.icon('schedule', size='sm')
                ui.label('AUTO-REFRESH: 30m')
                ui.label('|').classes('text-cyan-500/30')
                ui.label('THREAT LEVEL: ELEVATED')
        
        # Add New Target Section - Cyber Style (moved to top)
        with ui.card().classes('mb-8 p-6 w-full cyber-card'):
            with ui.row().classes('w-full items-center gap-4 mb-4'):
                with ui.element('div').classes('relative'):
                    ui.icon('add_circle', size='lg', color='cyan').classes('text-2xl')
                    ui.element('div').classes('absolute -inset-2 bg-cyan-500/20 rounded-full blur-md')
                ui.label('ADD NEW TARGET').classes('font-bold text-lg text-white font-mono tracking-wider')
            with ui.row().classes('w-full gap-4 mt-3 items-center'):
                new_url = ui.input('URL Target (https://...)').props('outlined').classes('cyber-input flex-grow')
                def save_target():
                    if new_url.value:
                        with Session(engine) as session:
                            session.add(Target(url=new_url.value))
                            session.commit()
                        target_cards_grid.refresh()
                        new_url.value = ""
                        ui.notify('✓ Target added to radar', color='positive')
                ui.button('ADD TO RADAR', on_click=save_target, icon='add').classes('cyber-btn cyber-btn-primary')

        @ui.refreshable
        def target_cards_grid():
            with ui.row().classes('w-full gap-8 mt-2 flex-wrap target-row-responsive'):
                targets = get_targets_data()
                if not targets:
                    with ui.card().classes('w-full p-12 text-center cyber-card'):
                        ui.icon('radar', size='xl', color='cyan').classes('text-5xl mb-4')
                        ui.label('SYSTEM STANDBY').classes('text-xl font-bold text-white font-mono tracking-wider')
                        ui.label('Add a target above to initiate patrol scan').classes('text-cyan-400/50 font-mono text-sm')
                for target in targets:
                    # Dynamic classes based on score
                    card_class = 'cyber-card-secure' if target.score >= 80 else ('cyber-card-warning' if target.score >= 50 else 'cyber-card-danger')
                    score_class = 'cyber-score-secure' if target.score >= 80 else ('cyber-score-warning' if target.score >= 50 else 'cyber-score-danger')
                    status_class = 'cyber-status-secure' if target.score >= 80 else ('cyber-status-warning' if target.score >= 50 else 'cyber-status-danger')
                    chart_color = '#00ff88' if target.score >= 80 else ('#ffaa00' if target.score >= 50 else '#ff3366')
                    with ui.card().classes(f'w-[600px] p-7 cyber-card {card_class}'):
                        with ui.row().classes('w-full items-center justify-between border-b border-[#1e293b] pb-3 mb-3'):
                            with ui.column().classes('gap-0'):
                                ui.label(f"{target.url}").classes('font-bold text-lg text-white truncate max-w-[350px]')
                                ui.label(f"IP: {target.ip_address}").classes('text-xs font-mono text-cyan-400/60')
                            with ui.row().classes('gap-1'):
                                def open_edit_dialog(t=target):
                                    with ui.dialog() as dialog, ui.card().classes('w-[450px] p-6 cyber-card'):
                                        ui.label('EDIT TARGET').classes('text-xl font-bold text-white font-mono mb-4')
                                        new_url_input = ui.input('URL Target', value=t.url).props('outlined').classes('cyber-input w-full')
                                        def save_edit():
                                            with Session(engine) as session:
                                                db_target = session.get(Target, t.id)
                                                db_target.url = new_url_input.value
                                                db_target.status, db_target.ip_address = "Belum Discan", "Belum Discan"
                                                session.add(db_target)
                                                session.commit()
                                            dialog.close()
                                            target_cards_grid.refresh()
                                            ui.notify('Target updated!', color='positive')
                                        with ui.row().classes('w-full justify-end gap-2 mt-4'):
                                            ui.button('Cancel', on_click=dialog.close).props('color=cyan flat')
                                            ui.button('Save', on_click=save_edit).props('color=indigo')
                                    dialog.open()
                                ui.button(icon='edit', on_click=lambda t=target: open_edit_dialog(t)).props('flat dense round color=cyan')
                                def delete_target(t_id=target.id):
                                    with ui.dialog() as dialog, ui.card().classes('w-96 cyber-card'):
                                        ui.label('DELETE TARGET?').classes('text-lg font-bold text-white font-mono')
                                        ui.label(f'Confirm removal of {target.url}').classes('text-cyan-400/60')
                                        with ui.row().classes('w-full justify-end gap-2 mt-4'):
                                            ui.button('Cancel', on_click=dialog.close).props('color=cyan flat')
                                            def confirm_delete():
                                                with Session(engine) as session:
                                                    db_target = session.get(Target, t_id)
                                                    if db_target:
                                                        session.delete(db_target)
                                                        histories = session.exec(select(ScanHistory).where(ScanHistory.target_id == t_id)).all()
                                                        for h in histories: session.delete(h)
                                                        session.commit()
                                                target_cards_grid.refresh()
                                                ui.notify('Target removed!', color='negative')
                                            ui.button('Delete', on_click=confirm_delete).props('color=red')
                                    dialog.open()
                                ui.button(icon='delete', on_click=lambda t_id=target.id: delete_target(t_id)).props('flat dense round color=red')
                        # Score and Status
                        with ui.row().classes('w-full items-center justify-between mb-3'):
                            with ui.column().classes('gap-0'):
                                status_icon = 'check_circle' if target.score >= 80 else ('warning' if target.score >= 50 else 'error')
                                with ui.row().classes('items-center gap-2'):
                                    ui.icon(status_icon, color=target.score >= 80 and 'green' or (target.score >= 50 and 'amber' or 'red'))
                                    ui.label(f"{target.status}").classes(f'font-bold font-mono text-sm px-3 py-1 rounded {status_class}')
                            with ui.column().classes('items-end gap-0'):
                                ui.label(f"{target.score}").classes(f'text-4xl font-extrabold {score_class}')
                                ui.label('/100').classes('text-cyan-400/40 text-sm font-mono')
                        # Mini Chart
                        with Session(engine) as session:
                            history = session.exec(select(ScanHistory).where(ScanHistory.target_id == target.id)).all()
                            times = [h.timestamp for h in history[-8:]]
                            scores = [h.score for h in history[-8:]]
                        if times:
                            ui.echart({
                                'xAxis': {'type': 'category', 'data': times, 'axisLabel': {'fontSize': 9, 'color': '#64748b'}, 'axisLine': {'lineStyle': {'color': '#1e293b'}}},
                                'yAxis': {'type': 'value', 'min': 0, 'max': 100, 'axisLabel': {'fontSize': 9, 'color': '#64748b'}, 'splitLine': {'lineStyle': {'color': '#1e293b'}}},
                                'series': [{'type': 'line', 'data': scores, 'smooth': True, 'areaStyle': {'opacity': 0.2, 'color': chart_color}, 'itemStyle': {'color': chart_color}, 'lineStyle': {'width': 2}}],
                                'grid': {'left': '12%', 'right': '5%', 'top': '5%', 'bottom': '20%'}
                            }).classes('w-full h-32')
                        else:
                            with ui.card().classes('w-full h-32 bg-[#0a0e17] flex items-center justify-center border border-[#1e293b]'):
                                ui.label('NO DATA').classes('text-cyan-400/40 font-mono text-sm')
                        # Action Buttons
                        def open_remediation_dialog(t=target):
                            with ui.dialog() as dialog, ui.card().classes('w-[650px] p-0 cyber-card'):
                                with ui.row().classes('bg-[#0a0e17] text-white p-4 items-center border-b border-[#1e293b] gap-3'):
                                    ui.icon('insights', size='lg').classes('text-amber-400')
                                    ui.label(f'INTELLIGENCE REPORT: {t.url}').classes('text-lg font-bold font-mono')
                                with ui.column().classes('p-5 gap-4'):
                                    with ui.card().classes('bg-red-500/10 border border-red-500/30 p-4'):
                                        with ui.row().classes('items-center gap-2 mb-2'):
                                            ui.icon('warning', color='red-400')
                                            ui.label('SCAN RESULTS').classes('font-bold text-red-400 font-mono')
                                        ui.markdown(t.last_alerts).classes('text-sm text-cyan-100/80')
                                    with ui.card().classes('bg-blue-500/10 border border-blue-500/30 p-4'):
                                        with ui.row().classes('items-center gap-2 mb-2'):
                                            ui.icon('lightbulb', color='cyan-400')
                                            ui.label('REMEDIATION').classes('font-bold text-cyan-400 font-mono')
                                        ui.markdown(t.remediation_notes).classes('text-sm text-cyan-100/80')
                                with ui.row().classes('p-4 flex justify-end border-t border-[#1e293b]'):
                                    ui.button('Close', on_click=dialog.close).props('color=cyan flat')
                                dialog.open()
                        with ui.row().classes('w-full gap-2 mt-3'):
                            ui.button('INSIGHTS', on_click=lambda t=target: open_remediation_dialog(t), icon='lightbulb').props('flat color=emerald').classes('cyber-btn flex-grow justify-center')
                            ui.button(icon='picture_as_pdf', on_click=lambda t=target: ui.download(generate_pdf_report(t.url, t.score, t.last_alerts.split('\n'), t.remediation_notes.split('\n')))).props('flat color=slate').classes('cyber-btn px-3')
        target_cards_grid()
        ui.timer(300.0, target_cards_grid.refresh)

# --- 5. RUNNER ---
scheduler = BackgroundScheduler()
# Scheduler memanggil patroli_core_logic yang di dalamnya sudah ada perintah broadcast refresh
scheduler.add_job(lambda: asyncio.run(patroli_core_logic()), 'interval', minutes=30)
scheduler.start()

fastapi_app = FastAPI()
ui.run_with(fastapi_app)

if __name__ in {"__main__", "__mp_main__"}:
    ui.run(
        port=8080, 
        title="PATROLI-WEB",
        favicon="🛡️",
        reload=False
    )